### ISSUE TITLE
Relaxed/loose URI's

### ISSUE THREAD

**Issue by bjartebore** [KSDaemon/wampy.js#102]
**Is your feature request related to a problem? Please describe.**
It would be useful if we could have the possibility to use relaxed/loose URI's when subscribing to topic. In my case I need to subscribe to some topics where I am not in the position to change the topics to validate to a strict URI.

**Describe the solution you'd like**
I would like the possibility to configure wampy to use the loose/relaxed type of URI validation described in the [Wamp Draft](https://wamp-proto.org/_static/gen/wamp_latest.html) 5.1.1.1
This could be done with a new option for the wampy instance named uriValidation that would accept strict or loose, with a default to strict.

Would you accept any pull requests for such a change?

**Comment by KSDaemon** [comment]
Well, yes. I think this way it will be usefull.

**Comment by KSDaemon** [comment]
Closed via PR #103
