### ISSUE TITLE
question about "HELLO" message

### ISSUE THREAD

**Issue by nolsong** [KSDaemon/wampy.js#11]
Hi, I have one question.

Are there any options to set 'Details'(or payload) when send the HELLO message?

below quotation is taken from [WAMP v2 draft](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-7.1.1).

> After the underlying transport has been established, the opening of a
   WAMP session is initiated by the _Client_ sending a "HELLO" message
   to the _Router_.
  "Details" is a dictionary that allows to provide additional
      opening information

       [HELLO, Realm|uri, Details|dict]

As I know, HELLO message will be sent to the router automatically when wampy's constructor is created. but I can not find any options to set 'Details' in case of using constructor and connection( ) method.
 
If there is no way now, do you have plan to support that feature?

Thank you.

**Comment by Seyun** [comment]
+1

**Comment by KSDaemon** [comment]
Hi all, guys! Well, right now there is no way to provide details. But, hmmm, why not to add a such functionality? ;) I'll have a look at that!

**Comment by nolsong** [comment]
Hi, sorry I'm late.

In my opinion, It's very easy way for this functionality to add 'helloDetails' attribute to the wampy's options.
And then helloDetails custom option will be merged with 'this._wamp_features' before HELLO message is sent. 
If there is no hellowDetails in the options, details include only wamp feature as before.
please check this [simple implementation](https://github.com/nolsong/wampy.js/commit/9bda8ad7f1f9362b78b60069dc27bd1ce3678f3f) and give me your opinion ;)

Cheers.

**Comment by KSDaemon** [comment]
Hi, @nolsong. I've just read WAMP Spec. Well, what router do you use? I didn't find any info about using custom attributes, provided with HELLO msg.

**Comment by nolsong** [comment]
Hi, my coworker has made a router himself and I use that. 
And ultimately we need to implement a session authentication, but It seem that Wampy.js doesn't provide authentication functionality yet. Is it right?

There will be two way to provide an authentication. 
firstly, implement advanced profile(CHALLENGE, AUTHENTICATE messages...) as WAMP spec.
secondly, just use a custom attribute with "HELLO" msg. we are using this way for auth, so WAMP client should send custom auth information via "HELLO" msg, and then router will reply with a "WELCOME" msg or "ABORT" msg to client.

if you have plan to implement an advanced profile, we'd prefer that way and we're willing to wait :)
if not, please consider alternative solution.

**Comment by KSDaemon** [comment]
Hi, @nolsong! Well, i have a plans to add CRA auth. There is already #10 about that. But anyway, i do not see any reason not to add a custom attributes to HELLO.
And that is done! ;)

**Comment by nolsong** [comment]
Thank you very much! :+1:
