### ISSUE TITLE
Wampy is not a constructor

### ISSUE THREAD

**Issue by Ned452** [KSDaemon/wampy.js#114]
Hi
I use Wampy.js with Node JS but when I try running app i get this error
`TypeError: Wampy is not a constructor`

Here is the code I use:

```
const Wampy = require('wampy');
const w3cws = require('websocket').w3cwebsocket;

let options = {
   ws: w3cws,
   realm: 'AppRealm'
};

let ws = new Wampy('ws://localhost:3000/ws', options);
```

Yours sincerely,
Nedim

**Comment by KSDaemon** [comment]
Hi @Ned452 
Try `const Wampy = require('wampy').Wampy;` :)

**Comment by Ned452** [comment]
@KSDaemon, thank you, this is working for me!)
