### ISSUE TITLE
Request for typings file

### ISSUE THREAD

**Issue by bradws** [KSDaemon/wampy.js#12]
Hi,
Is there any chance of having a Typescript 'typings' file .d.ts at all?
Cheers,

**Comment by KSDaemon** [comment]
Yes, there is a chance! :) I'll see how to get this.

**Comment by KSDaemon** [comment]
hi @bradws A few hours ago wampy.d.ts was merged into definitelyTyped repo! ;)

**Comment by bradws** [comment]
Is there any possibility of updating the typings for v3.0.2 at all?
Cheers,
bradws
