### ISSUE TITLE
How to use this project with a bundler?

### ISSUE THREAD

**Issue by bensampaio** [KSDaemon/wampy.js#128]
I am considering using this project in my React app in order to connect with an already existing WebSocket server that uses the WAMP protocol. In your README I only see examples on how to import wampy from Node.js. How can that be done in a browser? Please don't tell me this is a global dependency D:

**Comment by KSDaemon** [comment]
Hi @bensampaio! 
Well, just use it as you do with any other javascript module/dependency. Include it in your code using any js bundler (webpack, parcel, etc) and go on!

**Comment by KSDaemon** [comment]
Original README was written long ago :)

**Comment by bensampaio** [comment]
Hi @KSDaemon, thank you for your fast reaction. So jus to make sure I can `import {Wampy} from 'wampy';` and this will import browser code and not node code?

**Comment by KSDaemon** [comment]
Yep! 
I'll tell you one secret: there is no difference between node.js and browser version. The only difference is websocket object, which is provided as dependency in node.js env ;)

**Comment by bensampaio** [comment]
Haha good to know! Thank you for the clarification.

**Comment by KSDaemon** [comment]
Np! You're welcome! :)
