### ISSUE TITLE
Wampy > 2.0 does not work in Browser

### ISSUE THREAD

**Issue by martinpley** [KSDaemon/wampy.js#13]
Wampy 2.0.1, running in Chrome gives the following Error.
Also tested with Edge-Browser.
Seems to be a regression of commit 493dbe.

` ReferenceError: root is not defined`
`    at getWebSocket (wampy.js:190)`
`    at Wampy.connect (wampy.js:1135)`
`    at new Wampy (wampy.js:450)`

**Comment by KSDaemon** [comment]
Ough! Really stupid bug! @martinpley thanks for report! I'll fix it asap

**Comment by martinpley** [comment]
Thanks
