### ISSUE TITLE
Hypen in pubsub topic name breaks delivery

### ISSUE THREAD

**Issue by cameronelliott** [KSDaemon/wampy.js#135]
**Describe the bug**
When using this: `example.hello` topic name, messages get delivered okay.
When using this: `example-hello` topic name, messages do not get delivered.

**To Reproduce**
```js
"use strict";

// does not work
const topic = 'example-hello';

// does work fine
// const topic = 'example.hello';


const opts = {
    realm: 'realm1',
}
const ws = new Wampy('/ws', opts);
ws.subscribe(topic, function (dataArr, dataObj) {
    console.log('got it', dataArr);

});


const w2 = new Wampy('/ws', opts);
w2.publish(topic, 'hello-foo');
```

**Comment by cameronelliott** [comment]
I have been trying to understand this better, and I will note the following about the topic name `example-hello`

`example-hello` does match the [Relaxed URI rules in the spec](https://wamp-proto.org/_static/gen/wamp_latest.html#relaxed-loose-uris)   regexp: `^([^\s\.#]+\.)*([^\s\.#]+)$`

`example-hello` does NOT match the [Strict URI rules in the spec](https://wamp-proto.org/_static/gen/wamp_latest.html#strict-uris)   regexp: `^([0-9a-z_]+\.)*([0-9a-z_]+)$`

So, maybe the issue is that I just did not understand that Wampy requires topic names to conform to the strict URI rules published in the specification??
Is it true to say "Wampy requires topic names to conform to the strict URI rules in the specification?"

Thank you for any clarification.

**Comment by cameronelliott** [comment]
I have been reading up on this further, and this is what the spec says:

> While the above rules MUST be followed, following a stricter URI rule is recommended: URI components SHOULD only contain lower-case letters, digits and _.

Where the spec says `above rules`, it is referring to the  [Relaxed URI rules in the spec](https://wamp-proto.org/_static/gen/wamp_latest.html#relaxed-loose-uris).

So, from my understanding, **the spec says that the Relaxed URI rules must be followed**.
Yet, from my testing, Wampy will not pass messages unless they confirm to the  [Strict URI rules](https://wamp-proto.org/_static/gen/wamp_latest.html#strict-uris).

I think the spec could have done a better job of communicating here, **and I would guess their meaning was this**:

- Applications should use the strict spec.
- Client libraries should allow use of both the relaxed and strict spec.
- Routers should allow use of both the relaxed and strict spec.

I think the spec should also state whether the regex's are normative or non-normative. 
I personally would prefer that they be normative, because I find the language regarding URIs, the examples, and the regex's to
all communicate something slightly different.

**Comment by gammazero** [comment]
- Yes, applications should use the strict spec. This guarantees them a compatible URI.
- Client libraries may allow both, but a client library could choose to be opinionated about this and decide to restrict to only using strict.  This is likely as the library implementer does not want to handle issues arising from someone's use of a client not working with a router that is configured to only handle strict spec.
- Routers _should_ allow both, but that is a choice and is configurable.

**Comment by cameronelliott** [comment]
@gammazero Hey! just a fyi, this issue here: [Here](https://github.com/KSDaemon/wampy.js/pull/134) was required to get Wampy to share sessionid's with subscribers on Nexus.  Not an issue with Nexus, but maybe something you should know.

**Comment by KSDaemon** [comment]
Hi @cameronelliott!
I don't think you noticed that in the documentation:
```
* **uriValidation**. Default value: strict. Can be changed to loose for less strict URI validation.
```

And as @gammazero already mentioned, strict validation is preffered. In this case you can safely use any router and client and be sure about interop.
