### ISSUE TITLE
Question about 2nd parameter on subscribe callback

### ISSUE THREAD

**Issue by cameronelliott** [KSDaemon/wampy.js#136]
## question on usage

Is there a 'publish()' example where the 2nd parameter to the subscribe is filled in and defined?
I haven't been able to get dataObj be anything but undefined.
I'm a weak javascript programmer, so forgive me if this should be obvious.

Thanks,
Cameron

```js
const ws = new Wampy('/ws/', { realm: 'AppRealm' });
ws.subscribe('system.monitor.update', function (dataArr, dataObj) { console.log('Received system.monitor.update event!'); })
  .subscribe('client.message', function (dataArr, dataObj) { console.log('Received client.message event!'); })
```

**Comment by KSDaemon** [comment]
Hi! 
Well, it seems that example from the docs is right about it:
```javascript
ws.publish('user.modified', { field1: 'field1', field2: true, field3: 123 });
```
But you have mistake in your subscribe callback. Event callback is called with one hash-table parameter with following attributes:

- argsList: array payload (may be omitted)
- argsDict: object payload (may be omitted)
- details: some publication options object.

**Comment by KSDaemon** [comment]
Hope it helps!

Please read the documentation carefully

**Comment by cameronelliott** [comment]
> Hope it helps!
> 
> Please read the documentation carefully

@KSDaemon  

I think Wampy.js is fantastic, and you too, Konstantin! You are really nice. ❤️ 
**But I did read the documentation**  😢 
*My example is from the documentation*  :cry: :cry:

I submitted a PR to fix the documentation: [PR Fix README](https://github.com/KSDaemon/wampy.js/pull/137)
