### ISSUE TITLE
Tutorials/Help for node

### ISSUE THREAD

**Issue by bradws** [KSDaemon/wampy.js#15]
Hi,
You mention WAMPY is a 'browser-only' lib, but you've got example code for node:
```
// in node.js
w3cws = require('websocket').w3cwebsocket;
ws = new Wampy(null, { ws: w3cws });
ws = new Wampy('/my-socket-path', { ws: w3cws });
ws = new Wampy('ws://socket.server.com:5000/ws', { autoReconnect: false, ws: w3cws });
ws = new Wampy({ reconnectInterval: 1*1000, ws: w3cws });
```

Are you able to please provide a basic example (possibly with a package.json) to get WAMPY working with Node (i.e. installation of WebSocket, WAMPY, etc) ?

I'm unable to get this going in Node. (running in Browser is fine, though!)

(Ideally, I'm trying to get this working with Typescript in Node, but lets just get the JavaScript version working for me: one step at a time. I have it working with Typescript in the Browser just fine.)

Cheers.

**Comment by KSDaemon** [comment]
Hi, @bradws Sorry for delayed answer. 
Thanks for pointing out error in docs. Fixed.

Well, actually, there is no special setup for node, just a few lines of code. Here is from my own project:
```javascript
const Wampy = require('wampy');
const w3cws = require('websocket').w3cwebsocket;
let options = {  // these two options are mandatory
   ws: w3cws,
   realm: appConfig.WAMPRealm
};

let wampy = new Wampy(appConfig.WAMPUrl, options);
```

And that's all :)

**Comment by bradws** [comment]
Thanks. This worked perfectly.
