### ISSUE TITLE
WampyOptions type issue:  onError?: Callback | undefined;  Callback has no parameters

### ISSUE THREAD

**Issue by MichaelJCole** [KSDaemon/wampy.js#157]
**Describe the bug**
WampyOptions appears to have incorrect types for callback functions

**To Reproduce**

I'm trying to pass callback functions, but getting type errors.  The existing types on WampyOptions are this:

```
declare namespace wampy {
    type Callback = () => void;
    type ErrorCallback = (args: ErrorArgs) => void;
    type EventCallback = (args: DataArgs) => void;
    type SuccessCallback = (args: DataArgs) => void;
    type RPCCallback = (args: DataArgs) => RPCResult | void;
    type ChallengeCallback = (auth_method: string, extra: Dict) => string;
    ...
    interface WampyOptions
    {
        autoReconnect?: boolean | undefined;
        reconnectInterval?: number | undefined;
        maxRetries?: number | undefined;
        realm?: string | undefined;
        helloCustomDetails?: any;
        authid?: string | undefined;
        authmethods?: string[] | undefined;
        onChallenge?: ChallengeCallback | undefined;
        onConnect?: Callback | undefined;
        onClose?: Callback | undefined;
        onError?: Callback | undefined;
        onReconnect?: Callback | undefined;
        onReconnectSuccess?: Callback | undefined;
    }
}
```

The [usage example](https://github.com/KSDaemon/wampy.js/blob/9d11cf1a8b9c19cb0b5f88d54df93ffd596bd83d/README.md#usage-example) shows parameters.

```
const options: WampyOptions = {
  realm: REALM,
  onError: (args: ErrorArgs) => {
    console.log('Breakdown happened')
    return
  },
  onReconnect: function () {
    console.log('Reconnecting...')
  },
  onReconnectSuccess: function (welcomeDetails) {
    console.log('Reconnection succeeded. Details:', welcomeDetails)
  },
}
```

I'm guessing it's just an oversight.  I'd make a PR, but I couldn't find that file.

Thank you!

**Comment by KSDaemon** [comment]
Hi! :) 
Well, seems that typings are outdated. Its a community definitions (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/wampy)

Will be great if you could update them, or even add a typings to this wampy repo.

P.S. I have thoughts to rewrite wampy in typescript, but just had no time for this yet.

**Comment by MichaelJCole** [comment]
Hi Konstantin, I'm pretty new at typescript and might do more damage than good :-)  Thanks for your time!
