### ISSUE TITLE
Help in file transfer between clients

### ISSUE THREAD

**Issue by ethrbh** [KSDaemon/wampy.js#16]
hello,

I know the "ISSUE" is not a right forum to post questions, but unfortunately I did not find your email address, thus I just choosed this way.

So I am using your wampy project and I would like to do file transfer between two wamp clients. In the README, I can see an example for wamp.call where a backup file is transfered(?)

    ws.call('restore.backup', { backupFile: 'backup.zip' }, {...

I would like to ask you, do I understood right, the call method is the way how file can be transfered?

Thanks for your help.
/Robi

**Comment by KSDaemon** [comment]
Hi, @ethrbh !
Hmm, seems you misunderstood the example. I meant that the ws.call was invoked with meta-information about a backup that you want to restore, and not the file itself. Should probably correct the example. 
WAMP (as protocol) is not very suited for the transmission of binary data. But, you can do that, using a base64 encoding, just read the contents of file manually, encode it with base64 and pass to ws.call, and don't forget to decode it on the other side :) But, remember, that message size will increase approximately +30%

**Comment by KSDaemon** [comment]
Also, you can read related question thread on WAMP Google Groups: https://groups.google.com/forum/#!topic/wampws/IaXldipAJ_M

**Comment by ethrbh** [comment]
hello,

Thanks for your help. Now I can step over what should I do after reading the attached link too.

thanks again,
/Robi

**Comment by KSDaemon** [comment]
You are welcome! :)
