### ISSUE TITLE
Support for wamp.json instead of wamp.2.json

### ISSUE THREAD

**Issue by MakeShiftArtist** [KSDaemon/wampy.js#179]
**Is your feature request related to a problem? Please describe.**
I'm forced to use a library or write my own code to change the wampy instance to use wamp.json instead of wamp.2.json because an app I'm reverse engineering uses wamp.json

**Describe the solution you'd like**
Easy way to configure this. like
```js
const wampy = new Wampy('url', {})
wampy.setProtocol('wamp.json')
```
or even better
```js
const wampy = new Wampy('url', {protocol: 'wamp.json'})
```

**Describe alternatives you've considered**
If a feature like this already exists, then I'd be glad to adopt that instead.

**Additional context**
The library I've been using is [wampy-patch](https://github.com/ifunny-co/wampy-patch/blob/main/index.js).

Hopefully this can help you understand the issue I'm running into

**Comment by KSDaemon** [comment]
Hi @MakeShiftArtist! 
Well, can you try to update/refactor the broken app instead of monkey patching wampy? 
In general view — it is just a very specific problem, and not wanted to provide an extra public API just for that...

**Comment by KSDaemon** [comment]
You can workaround this for example by providing your own websocket instance which is a wrapper around native one, so you can patch protocols parameter on the fly:
```javascript
class yourWebsocketInstance (url, protocols) {
  return new window.websocket(url, `wamp.json`)
}

wampy = new Wampy('wss://socket.server.com:5000/ws', {
    ws: yourWebsocketInstance
});


```

**Comment by MakeShiftArtist** [comment]
> Well, can you try to update/refactor the broken app instead of monkey patching wampy?

I don't own the broken app, I'm reverse engineering it, so unfortunately this is not an option.

As for the custom WebSocket, I'll have to try this next time I'm working on it, but last time I couldn't get it to connect when using the custom WS.
