### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by bradws** [KSDaemon/wampy.js#18]
Hi,

I'm having issues installing Wampy. I'm using Node v5.10.1 and npm v 3.8.3

When i do
`npm install wampy`
in an empty folder with no `package.json` file, I get a whole heap of errors in red.

If i do have a  `package.json` file, and do
`npm install wampy --save` i still get a whole heap of errors.

The first 3 errors (out of about  100) are:
`
C:\Users\Brad\.node-gyp\5.10.1\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [C:\DEV\testwampyinstall\node_modules\websoc
ket\build\bufferutil.vcxproj]
C:\Users\Brad\.node-gyp\5.10.1\include\node\v8.h(336): error C2059: syntax error : 'using' [C:\DEV\testwampyinstall\node_modules\websocket\build\bufferutil.vcx
proj]
C:\Users\Brad\.node-gyp\5.10.1\include\node\v8.h(469): error C2988: unrecognizable template declaration/definition [C:\DEV\testwampyinstall\node_modules\websoc
ket\build\bufferutil.vcxproj]
`

I *have* installed Wampy before just fine with previous versions, but not this latest one.

Can anyone please help ?!?

**Comment by KSDaemon** [comment]
hi, @bradws !
Well, wampy itself doesn't use node-gyp. AFAIK, node-gyp is used by websocket library, which is a dependency. But, it was last updated on september 2015.... (see https://github.com/theturtle32/WebSocket-Node for more info).
Have you tried to update npm to latest one?

**Comment by KSDaemon** [comment]
btw, do you update visual studio?

**Comment by KSDaemon** [comment]
Quick look at google shows, most of same errors are related to VS somehow. https://www.google.ru/search?client=opera&q=v8.h(336)%3A+error+C2988%3A+unrecognizable+template+declaration%2Fdefinition+websoc+ket%5Cbuild%5Cbufferutil.vcxproj&sourceid=opera&ie=UTF-8&oe=UTF-8

**Comment by bradws** [comment]
Hi,
But how do you actually install Wampy from node now? I have nothing to to
with Visual Studio (although I am on a windows box).
I have the latest versions of Node and NPM.
`npm install wampy`
still gives all thoes red error messages when installing.
Saying that though, .\node_modules\wampy\build\wampy.min.js does exist
after installation.
How do you install it?
Thanks again,
bradws.

**Comment by KSDaemon** [comment]
Hi!
Well... I'm om Mac. 
Here it works as expected:
```
kostik@GrayWolf:~/TMP/> mkdir test                                                                                                                                 [9:11] cmd#2784
kostik@GrayWolf:~/TMP/> cd test                                                                                                                                    [9:11] cmd#2785
kostik@GrayWolf:~/TMP/test/> npm i wampy                                                                                                                           [9:11] cmd#2786

> websocket@1.0.23 install /Users/kostik/TMP/test/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/Users/kostik/TMP/test
└─┬ wampy@3.0.0
  ├─┬ msgpack5@3.3.0
  │ ├─┬ bl@1.1.2
  │ │ └── readable-stream@2.0.6
  │ ├── inherits@2.0.1
  │ └─┬ readable-stream@2.1.4
  │   ├── buffer-shims@1.0.0
  │   ├── core-util-is@1.0.2
  │   ├── isarray@1.0.0
  │   ├── process-nextick-args@1.0.7
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.2
  └─┬ websocket@1.0.23
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── nan@2.3.3
    ├─┬ typedarray-to-buffer@3.1.2
    │ └── is-typedarray@1.0.0
    └── yaeti@0.0.4
```

Did you try it from scratch and in empty project?

**Comment by bradws** [comment]
Well, I get basically get the same as you!

I get everything from the beginning up to and including the 

`
> (node-gyp rebuild 2> builderror.log) || (exit 0)
`

statement.

Then lots of evil red error messages.

Followed by everything from and including the statement
`
/Users/kostik/TMP/test
`

all the way to the end.

I ran the test installs with and without `package.json` and with an empty project and still these error messages appear (using Node v6.2.0 & Npm v3.8.9 )
Upon more detailed inspection, all my evil red error messages do (as you noted) seem to be related to Visual Studio. So maybe I'll ignore them for now)
I can confirm that the Wampy install seems to have installed just fine as I can see from my npm install Wamp output and comparing with yours. I also seem to have all the files and folders one would expect.

Hmmm. Well at this point I'll assume everything is installed correctly, do some dev, and see if it works. I'll just ignore the messages for now and see if things work as expected!

(By the way,  I got WAMPY working as an Angular 2 service!)

Cheers,
bradws

**Comment by KSDaemon** [comment]
Mmmmm.... I can just suggest to try older versions of node %)
If you are usign wampy just on client side, you can totally ignore warnings, cause they are related only to websocket package, that is used in node.js env! 

> By the way, I got WAMPY working as an Angular 2 service!
Cool! :)

**Comment by bradws** [comment]
Hi again KS,

I'm getting an error in Chrome and Firefox when including `wampy.min.js` (also `wampy.js`) in a simple html file. (v3.0.0).

Can you take a look at this at all?

Cheers again.

```html
<html>
  <head>
    <title>testwampyserver1a</title>

    <!-- Wampy 3.0.0 -->
    <script src="node_modules/wampy/build/wampy.min.js"></script>

  </head>

  <!-- 3. Display the application -->
  <body>
    <h1>Loading...</h1>
  </body>
</html>
```

![chromeerror](https://cloud.githubusercontent.com/assets/9676439/15452472/0bef35b4-2022-11e6-9531-a0745239cb3c.jpg)

![fferror](https://cloud.githubusercontent.com/assets/9676439/15452478/3644c7ca-2022-11e6-8001-bdddb37462e3.jpg)

**Comment by KSDaemon** [comment]
Hi, @bradws! Thanks for pointing that out! Version 3.0.1 should fix that!

**Comment by bradws** [comment]
Thank-you. Looking forward it ....

**Comment by bradws** [comment]
Wampy 3.0.2 no longer has these browser errors and works perfectly now. 
Thanks for the speedy update!
