### ISSUE TITLE
Request for Typings for v3.0.2

### ISSUE THREAD

**Issue by bradws** [KSDaemon/wampy.js#19]
Hi,

Is there any possibility of updating the Typings Definitions to v3.0.2 at all?

Cheers,
bradws

**Comment by KSDaemon** [comment]
Hi, @bradws! Sorry for delayed answer, i'm on vacation right now. But, yes, i'll update typings to current version after returning.

**Comment by bradws** [comment]
Also, I'm unable to get it working with Typescript in Node (non-browser). Are you able to provide an example at all?
(I can't seem to get it connecting by providing the correct imports and don't know how to set it up in code, etc.)
Cheers.

**Comment by KSDaemon** [comment]
@bradws Hmm. Well, The screenshot and code above is not the same :) Can you show the real code that fails? Maybe gist?

**Comment by bradws** [comment]
Sorry, I can't show you working code. I'm still unable to get Wampy working with Typescript at all, can you provide a very simple working example? This is what I've done:

## 1. Setup
I have project called `'testwampyserver4'` and created a folder `'testwampyserver4'`.
Inside the folder, I have minimal `package.json` file which is:

```
{
  "name": "testwampyserver4",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "devDependencies": {
    "typescript": "^1.8.10",
    "typings": "^1.0.4"
  },
  "dependencies": {
    "wampy": "^3.0.2"
  }
}
```

This has all been installed correctly with `>npm install` and seems to be fine.

I then installed the Wampy typings declaration files.

`>npm run typings init`
`>.\node_modules\.bin\typings install dt~wampy --global --save`

which resulted in my `typings.json` file:

```
{
  "name": "testwampyserver4",
  "dependencies": {},
  "globalDependencies": {
    "wampy": "registry:dt/wampy#3.0.0+20160619023348"
  }
}
```

This seems to be as expected with the correct `./typings/` folder and files one would expect (with the Wampy declaration files in `./typings/globals/wampy/index.d.ts`)

I have a minimal `server.ts` file (first 2 lines of [wampy-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/wampy/wampy-tests.ts) )

```
import Wampy from 'wampy';
var ws = new Wampy('http://wamp.router.url', {realm: 'WAMPRealm'});
```

## 2. Compile

Now I'm ready to compile with Typescript.

My `tsconfig.json` is simply (nothing unusual):

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```

and I compile with:

`>npm run tsc`

It seems to build fine with no errors with the output `server.js`:

```
"use strict";
var wampy_1 = require('wampy');
var ws = new wampy_1.default('http://wamp.router.url', { realm: 'WAMPRealm' });
//# sourceMappingURL=server.js.map
```

## 3. Run

However, when I run it with

`>npm start`

I get error:

![wampy](https://cloud.githubusercontent.com/assets/9676439/16175735/de1800f2-362a-11e6-8ce9-919cf2ab1211.jpg)

...or if I run it with

`>.\node_modules\.bin\tsc server.ts`

I get error:

`server.ts(1,19): error TS2307: Cannot find module 'wampy'.`

## 4. Possible problems

* It's as though Typescript cannot 'see' wampy at all; it can't `new` it.
* Also, I'm not 100% sure if the `import Wampy from 'wampy';` statement is even correct ?!?
* I believe Wampy needs websocket for Node, however I can see it was installed as a dependency for Wampy. Do I need the websocket declaration files (I would have thought not)?
* I noticed in  [wampy-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/wampy/wampy-tests.ts) a reference to `node.d.ts` - is this needed? how to install it?

Are you able to provide a very simple example to refer to?
Sorry bout all the questions. I'm learning all this stuff (already learnt heaps!). The client-side Angular2 service is working perfectly with Wampy. I've got the server component working with AutobahnJS but I'd rather keep the Wamp technology consistent. I'm so close....

Thanks heaps again,
**bradws.**

**Comment by KSDaemon** [comment]
@bradws Great! :)
