### ISSUE TITLE
Crossbar tests are timing out

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#190]
**Describe the bug**
 
``` 
  447 passing (36s)
  2 failing
  
 1) Wampy.js with Crossbar
       Works with Json serializer:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/mendonlu/wampy.js/test/wampy-crossbar-test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) Wampy.js with Crossbar
       works with Msgpack serialization:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/mendonlu/wampy.js/test/wampy-crossbar-test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**To Reproduce**
1. Run "npm run test" in latest dev branch

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - node v16.17.1
 - Version of Wampy.js library: 7.0.0-rc10
 - WAMP Router and version: idk

**Comment by KSDaemon** [comment]
Hey! @lucasrmendonca can you check at your side, because all CI actions with tests works well. And I even tried to run tests locally with XB docker image — also no problems:
```
  Wampy.js with Crossbar
    ✔ Works with Json serializer
    ✔ works with Msgpack serialization
```

**Comment by lucasrmendonca** [comment]
I've noticed when I change the following line the tests pass, but I have no idea why, I'm not familiar with Mocha:

```
describe('Wampy.js with Crossbar', function () {
    this.timeout(0); // <--- changed from 10000 to 0
    
    ...
```

**Comment by KSDaemon** [comment]
Well. 0 — disables timeout at all. 
Do you have XB instance up and running prior to run `npm test` ?

**Comment by KSDaemon** [comment]
If you want to run tests locally and do not have an XB instance, you can run `npm run test:node-no-crossbar`

**Comment by lucasrmendonca** [comment]
> Do you have XB instance up and running prior to run npm test ?
Nope... that's probably why haha 👀

> If you want to run tests locally and do not have an XB instance, you can run npm run test:node-no-crossbar
Thanks! I'll run this one instead then
