### ISSUE TITLE
I remember some comparison with other libs... where did it go?

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#197]
I remember seeing a comparison table between WampyJs and Autobahn-Js not sure if it's still there or if it was removed. 

This link no longer works: https://github.com/KSDaemon/wampy.js#quick-comparison-to-other-libs

**Comment by KSDaemon** [comment]
Yep, that was removed as it is outdated. 
Because wampy now also uses async/await approach. Even it is more lightweight, modular (and maybe faster/less memory) but without concrete numbers it cost nothing. MB I'll make some measurements later...

**Comment by KSDaemon** [comment]
So I'll close this.
