### ISSUE TITLE
My thoughts on replacing "lightweight" with "feature-rich"

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#198]
So, I've noticed Wampy's description in the README has changed from "lightweight" to "feature-rich". 

Personally, what got me into using it was the "lightweight" keyword itself, as I was looking for an alternative to autobahn-js because Webpack was complaining that it was too big to bundle into my application.

Now I'm using Wampy, which is way lighter and easy to use. Maybe if I saw "feature-rich" right off the bat I would think that it would be bigger and with more features when compared to autobahn-js and wouldn't consider it...

**Comment by KSDaemon** [comment]
Ouh! Good point! :) 
Let's return it back!

**Comment by KSDaemon** [comment]
And yeah, ab — is bundled with all necessary deps, so it is soooo heavy.... Wampy is modular. I even have plans to create a few crypto wrappers so it can be used with tweetnacl or libsodium depending of what already exists in the projects, thus minimizing total bundle.

**Comment by lucasrmendonca** [comment]
Let's keep both then, feature-rich and lightweight
