### ISSUE TITLE
URI validation

### ISSUE THREAD

**Issue by jarkt** [KSDaemon/wampy.js#20]
I can subscribe the channel "de.abc-de.test", I can publish too, but when I try to call or register a remote procedure with this name, I get the message "Topic URI doesn't meet requirements!".
The URI is ok, see: https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-5.1.1

**Comment by KSDaemon** [comment]
Hi, @jarkt! Sorry, for delayed answer, i'm on vacation right now. 
Well, actually, wampy implements strict uri check. So only letters, digits and "_" are allowed. See https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-5.1.1.2

Are you sure, that you is really subscribed? A quick look to code, shows, that it is not allowed. Right after calling .subscribe() can you call .getOpStatus() and check the result? Is it really ok?

**Comment by KSDaemon** [comment]
Hi, @jarkt. I think you are wrong. You can do nothing with topics with such names. 
Yes, wampy doesn't throw errors, so subscribe('de.abc-de.test', { ... }) doesn't throw error and return wampy object.
But, you can check errors in a few ways:

Just call getOpStatus() right after calling subscribe or any other method, and check the result. You'll get `{ code: 1, description: "Topic URI doesn't meet requirements!" }`

Or try to subscribe providing error handler:
```
ws.subscribe('de.abc-de.test', {
   onSuccess: function () { console.log('Successfully subscribed to topic de.abc-de.test'); },
   onError: function (err) { console.log('Subscription to de.abc-de.test failed with error: ' + err); },
   onEvent: function (data) { console.log('Received topic de.abc-de.test event'); }
});
```
And you will get error.
So, wampy works as expected.
