### ISSUE TITLE
Some questions about "prefer-const" rule warnings...

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#208]
There are some warnings from ESLint rule "prefer-const" that I left unchanged because I wasn't sure how to fix them, I'd appreciate some help with them:

```
wampy.js/test/fake-ws-set-protocol.js
17:5  warning  'WebSocket' is never reassigned. Use 'const' instead prefer-const
41:5  warning  'setProtocol' is never reassigned. Use 'const' instead  prefer-const

wampy.js/test/fake-ws.js
30:5  warning  'WebSocket' is never reassigned. Use 'const' instead
 ```
1) Aren't WebSocket and setProtocol a `class WebSocket` and a `function setProtocol` declaration ? Is it safe to rewrite them like this instead of assigning them to a `let` ?

```
wampy.js/test/wampy-common-test.js
1844:21  warning  'reqId' is never reassigned. Use 'const' instead  prefer-const
1875:21  warning  'reqId' is never reassigned. Use 'const' instead  prefer-const
```
2) Here I'm a bit confused, I'm not too familiarized with this, but 'reqId' seems to be used before it is declared, as an argument of `wampy.cancel(reqId ...` is it supposed to be like this? Is it possible to rewrite it using `const` instead?

**Comment by KSDaemon** [comment]
I'll have a look! Thnx for pointing!

**Comment by KSDaemon** [comment]
Besides `reqId` all warnings may be fixed. In case of `reqId` eslint can't figure out that `reqId` can be set only after making a call. So I just disable that specific checks for concrete 2 lines.
