### ISSUE TITLE
Thoughts on adding Prettier Code Formatter

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#209]
I have been using https://prettier.io/ in other projects and it's been useful, what are you thoughts on adding it to Wampy?

Pros:
- More consistent formatting
- Auto whitespace trimming
- Auto word-wrapping

Cons:
- Less freedom of format customization, as prettier is very opinionated
- Another config file cluttering our root folder
- Would have to add a big commit with cosmetic-only changes, messing with the git history a bit

**Comment by KSDaemon** [comment]
I prefer to have full control over the formatting. Eslint provides pretty good formatting options alongside the checks with the configuration you want. So there is no practical need to jump there.
