### ISSUE TITLE
Addition of the ticket auth method and others

### ISSUE THREAD

**Issue by iscriptology** [KSDaemon/wampy.js#21]
Thanks for the great work!

**Comment by KSDaemon** [comment]
Hi! Thnx! 
Any new auth method can be implemented as external plugin like [WAMP-CRA](https://github.com/KSDaemon/wampy-cra) is done. It's rather simple. Will be great, if you'll try to make it by yourself. I can review and help ;)

**Comment by KSDaemon** [comment]
Finally done! :)
