### ISSUE TITLE
Suggestion: .getOptions() and .setOptions()

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#215]
This is a breaking change, but I feel .options() being at the same time a getter and a setter depending on whether it has parameters or not is a bit of an anti-pattern and kinda confusing for the user.

What are the impacts of changing the API to .getOptions() and .setOptions()?

**Comment by KSDaemon** [comment]
Well... It's hard to say, are these variants in use... I would prefer, if you'd like to add new methods and mark old `.options()` as deprecated, mb add message to log if it is used... And then remove it, for example in the next main release...

**Comment by lucasrmendonca** [comment]
Cool! Good suggestion. This way it'll still be backwards compatible
