### ISSUE TITLE
Can't import Wampy

### ISSUE THREAD

**Issue by konpaka** [KSDaemon/wampy.js#23]
How to properly import wampy into TypeScript project?

Wampy.js installed with
```bash
typings install dt~wampy --global --save && npm install wampy --save
```
Trying to import Wampy:
```ts
import {Wampy} from "wampy";
```
`npm start` produces this error: 
```
error TS2305: Module '"wampy"' has no exported member 'Wampy'.
```

Next I tried to import as I have seen [here](https://forum.ionicframework.com/t/ionic-2-import-wampy-and-using-it/57896/3):
```ts
import * as Wampy from "wampy";
```
Getting
```
error TS2304: Cannot find name 'Wampy'.
```

UPD: Trying

```ts
import {wampy} from "wampy";
// some code
this.ws = new wampy('ws://127.0.0.1:9000', {
    realm: 'realm1',
    onConnect: () => {
        console.log('Connected to Router!');
    }
});
```
Getting
```
error TS2305: Module '"wampy"' has no exported member 'wampy'.
```

**Comment by youmad** [comment]
Now I currently using kinda workaround:
I have manualy added `<script src="node_modules/wampy/build/wampy.min.js"></script>` to index.html and declared Wampy as any.
```ts
declare var Wampy: any;
```

**Comment by konpaka** [comment]
Now I currently using kinda workaround:
I have manualy added `<script src="node_modules/wampy/build/wampy.min.js"></script>` to index.html and declared Wampy as any.
```ts
declare var Wampy: any;
```

**Comment by KSDaemon** [comment]
Hi, @konpaka! Well, i'm not a guru in typescript. But i can say next:
You are trying to import wampy module in typescript, which in fact transpile it to js, using ES syntax, which is not supported by wampy and node.js at a moment. 
You can take a look at http://stackoverflow.com/questions/18378503/importing-node-modules-with-typescript. Wampy definitions are available at definitelytyped.org.
