### ISSUE TITLE
NonExistRPCInvocationError is not being used anywhere

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#248]
Is it safe to remove it from errors.js?

**Comment by KSDaemon** [comment]
Well... The message `NON_EXIST_RPC_INVOCATION` is logged here: https://github.com/KSDaemon/wampy.js/blob/dev/src/wampy.js#L1319

But to the server is returned wamp spec expected message. 
So from one side yeah, it is not used... Well, we can remove it and add later if we need it
