### ISSUE TITLE
Inconsistent return values from RPC

### ISSUE THREAD

**Issue by gertsonderby** [KSDaemon/wampy.js#26]
When making RPCs using `Wampy#call()`, I am getting inconsistent onSuccess callback parameters. In some cases, I get just the returned data from the function (i.e. if the RPC handler returns an object, just that object is given in the callback); in other cases, I also get an empty array as first parameter to the callback, and then the data I want as the second parameter.

As a workaround I have made my wrapper detect if the first parameter is an empty array, in that case using the second parameter, but I'd like to know what is actually going on. Is this a bug, or am I just using the library wrong? I couldn't find anything in the documentation that helped.

**Comment by KSDaemon** [comment]
Hi, @gertsonderby! 
Answering here too :)

4.0.0 version was extended and updated, so there are some backward incompatible changes.

* Error callbacks now receive more than 1 parameter. In most cases it now is called with (Error|uri|string, Details|object). In some cases, like CALL, callback is called with (Error|uri|string, Details|object, Arguments|array, ArgumentsKw|object).
* Event callback for subscibed topic now receives 2 parameters: (Arguments|array, ArgumentsKw|object). It allows to receive array-like and hash-table payload at the same time. So, if your app is expecting to receive object-like payload in first argument, now you should add second one, and use it.
* Same rule as above applies to RPC result callback.

This is written in migrating guide, but i shall add this to main docs!

**Comment by gertsonderby** [comment]
Much appreciated. I'll check and verify that this is the behavior I'm seeing. To clarify: If the procedure handler returns array-like data, it will be the first arg, if anything else, it will be the second?

**Comment by gertsonderby** [comment]
Indeed, that does look like the behavior. Thanks for the clarification. :-)

**Comment by KSDaemon** [comment]
Great! You are welcome! :)
