### ISSUE TITLE
depending on window makes wampy unusable for webworkers 

### ISSUE THREAD

**Issue by eflauzo** [KSDaemon/wampy.js#28]
this logic

`scheme = window.location.protocol === 'https:' ? 'wss://' : 'ws://';`

in getServerUrlBrowser

set implicit requirement that window must exists which is not the case if code executed within WebWorker, there should be way to explicitly specify scheme or connection URI, to avoid requirement for window to exist.

**Comment by KSDaemon** [comment]
Hi, @eflauzo. I've made some fix. So, if you specify full URL, like: ws://myhost.mydomain.org/wamp-router-path — getServerUrlBrowser will not try to use window object.

**Comment by eflauzo** [comment]
awesome. 
 confirmed, issue fixed now.

**Comment by KSDaemon** [comment]
Great! 👍
