### ISSUE TITLE
null value in argList causes crossbar.io router exception

### ISSUE THREAD

**Issue by samson84** [KSDaemon/wampy.js#29]
Hi, 

1. register a callee function
2. callee function throws a custom error with argsDict but without argsList property
3. wampy.js handle this that, adds null to the argsList: https://github.com/KSDaemon/wampy.js/blob/dev/src/wampy.js#L999
4. wamp router throws protocol error and immediately close the connection because of type of the argList is None instead of Dict.

The wampy sends the following ERROR message:
`"[8,68,1,{},\"custom.error\",null,{\"message\":\"This error should be thrown\"}]"`

Causes the following error in crossbar.io router:
```
crossbar-service_1  | [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] Traceback (most recent call last):
crossbar-service_1  |   File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
crossbar-service_1  |     for msg in self._serializer.unserialize(payload, isBinary):
crossbar-service_1  |   File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
crossbar-service_1  |     msg = Klass.parse(raw_msg)
crossbar-service_1  |   File "/usr/local/lib/python3.5/site-packages/autobahn/wamp/message.py", line 1036, in parse
crossbar-service_1  |     raise ProtocolError("invalid type {0} for 'args' in ERROR".format(type(args)))
crossbar-service_1  | autobahn.wamp.exception.ProtocolError: invalid type <class 'NoneType'> for 'args' in ERROR

```

My custom error definition in node.js:

```javascript
function WampError(uri, message) {
    Error.captureStackTrace(this, this.constructor);
    this.uri = uri || 'wamp.error';
    this.details = {};
    //this.argsList = [];
    this.argsDict = {
        message,
    };
}
require('util').inherits(WampError, Error);
```

The WAMP standard is a little bit ambiguous on this topic:
https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-6.7
Recommends, that not pass empty arrays, simple skip them. --> this causes also a same type of error. 

On the other hand the https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-9.2.5
refers to a position based argument passing. 

A better solution can be to pass an empty array instead of `null` to the mentioned line.

**Comment by KSDaemon** [comment]
Hi, @samson84 ! Thanks for ur reporting. As i can see, crossbar disallows null objects... And, yes, you are right, there are some gaps in spec. I'll update wampy to send empty arrays in such cases. I've looked through the spec, and feel — it will be right way to handle such cases.

**Comment by samson84** [comment]
Thanks.

**Comment by samson84** [comment]
I have asked a kind of questions from the autobahn / crossbar.io creators also: https://github.com/crossbario/autobahn-python/issues/779
