### ISSUE TITLE
clarification of error usage in a documentation

### ISSUE THREAD

**Issue by samson84** [KSDaemon/wampy.js#30]
Hi,

I made some experiments with the error handling, and have a docs update recommendation: 

in readme.md:
> Also it is possible to abort rpc processing and throw error with custom application specific data. This data will be passed to caller onError callback. Exception object with custom data may have next attributes:
> 
> uri. String with custom error uri.
> details. Custom details object.
> argsList. Custom arguments array.
> argsDict. Custom arguments object.
> 

According to the standard the details object is used by the router not by the original caller or publisher . The main reason of this object to extend the protocol for the further features. It is not really guaranteed that this object will be passed back to the caller / publisher (and the crossbar.io router implementation actually working this way). However it is not said explicitly. 
https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-6.1

According to the INVOCATION ERROR message definition of the standard argList and argDict objects sends back to the caller / subscriber, even it is said explicitly.
https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-9.2.5

If you agree, I am happy to contribute of the correction.

Thanks for the answer, 
Daniel

**Comment by KSDaemon** [comment]
O, great! That is always welcome!

**Comment by KSDaemon** [comment]
Done by @samson84 !
