### ISSUE TITLE
Using kawanet/msgpack-lite as msgpackCoder

### ISSUE THREAD

**Issue by livelazily** [KSDaemon/wampy.js#32]
[kawanet/msgpack-lite](https://github.com/kawanet/msgpack-lite) is much faster and size smaller than msgpack5

Here is the benchmarks:
https://github.com/kawanet/msgpack-lite#benchmarks

Using msgpack-lite for wampy-all.min.js can probably reduce the file size by half

**Comment by KSDaemon** [comment]
Hi @livelazily! 
Yes, i know about msgpack-lite and all others implementations. But there is one problem with msgpack-lite — it isn't compatible with crossbar WAMP router msgpack implementation. But msgpack5 works well with crossbar and Wiola without any problems. That's why it was choosen.
