### ISSUE TITLE
Connection to server is stuck most of the time

### ISSUE THREAD

**Issue by gazlu** [KSDaemon/wampy.js#34]
I am connecting to WampSharp server implementation and connection to the server most of the time stuck. If I connect though wampsharp client it is always successful, any thoughts. Same thing with autobahn client.

![image](https://cloud.githubusercontent.com/assets/1546523/24410573/feae0204-13f0-11e7-9dbf-d4e6d095f796.png)

**Comment by 421p** [comment]
Hi @gazlu can't really help you without seeing a code.
Take a look of this example: https://github.com/421p/wampy-via-wampsharp
it might help you :smile:

**Comment by KSDaemon** [comment]
Well, @gazlu as far as i can see, it's a wampsharp problem, not wampy or autobahn, because they all work well with different wamp router implementations. 
If you want to receive some sort of help — please provide more details: browser, log of every request to wamp router (raw data + headers).

**Comment by KSDaemon** [comment]
Closing due to inactivity. Feel free to reopen with detailed description.
