### ISSUE TITLE
Feature request: Event Retention

### ISSUE THREAD

**Issue by ialse** [KSDaemon/wampy.js#347]
I did not find an implementation of getting the last published message when subscribing to a topic. Has this been implemented or planned in future releases?

Read more here:
https://github.com/wamp-proto/wamp-proto/blob/da34d9bd833beeb6f9cc8bc89faf8138d710aa78/rfc/text/advanced/ap_pubsub_event_retention.md#event-retention

**Comment by KSDaemon** [comment]
Hi @ialse sorry, this feature is not supported yet. But feel free to make an PR with the implementation ;) Your help would be highly welcomed!
