### ISSUE TITLE
Unhandled Rejection at Promise

### ISSUE THREAD

**Issue by PatrLind** [KSDaemon/wampy.js#386]
**Describe the bug**
When reconnecting to the server I often get errors like: `register for already registered procedure 'TOPIC'`
When this happens the _wsOnMessage doesn't handle the error and create an unhandled rejection at promise error.

**Expected behavior**
The error should probably be handled by a try catch in _wsOnMessage(). 

**Stack trace**
```
RegisterError: Wamp error
    at Wampy._onErrorMessage (file:///PROJECT_PATH/node_modules/wampy/src/wampy.js:1078:39)
    at 8 (file:///PROJECT_PATH/node_modules/wampy/src/wampy.js:875:54)
    at Wampy._wsOnMessage (file:///PROJECT_PATH/node_modules/wampy/src/wampy.js:908:19)
    at WebSocket._ws.onmessage (file:///PROJECT_PATH/node_modules/wampy/src/wampy.js:777:46)
    at callListener (/PROJECT_PATH/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/PROJECT_PATH/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/PROJECT_PATH/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at /PROJECT_PATH/node_modules/ws/lib/receiver.js:608:16
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by KSDaemon** [comment]
Hi @PatrLind thnx for filing the bug! I'll have a look into that! Happy New Year!

**Comment by PatrLind** [comment]
I have been looking more at this today, and I cannot figure out why there is an unhandled rejection. I have tried to add try catches and async catch handlers everywhere I can think of, but nope... Even using the debugger I cannot find it.

Anyway, I figured out the reason to why there is an exception to begin with.
I have had lots of issues with the client being unable to reconnect when the network fails. This issue was reported by another user here: https://github.com/KSDaemon/wampy.js/issues/276

My workaround to this has been to create a custom WebSocket handler (see below for reference) that can detect the error and try to make wampy reconnect. However, when the reconnect happens is when I get the unhandled rejections. It turns out that the _renewRegistrations() function doesn't supply the advanced options parameter. It just leaves it empty. This causes issues, since I used those options when registering the functions. 
So options when registering was: `{"invoke":"roundrobin"}`
And options when re-registering was: `{}`
The resulting error (that is unhandled) is: `wamp.error.procedure_exists_with_different_invocation_policy,register for already registered procedure 'TOPIC' with conflicting invocation policy (has roundrobin and single was requested) `

The function with the issue is here:
https://github.com/KSDaemon/wampy.js/blob/7d0423c51dca5336de9ab23a2c29cdb32df42511/src/wampy.js#L1510C5-L1520

My WebSocket extension:
```typescript
import { ClientRequestArgs } from "http";
import WebSocket from "ws";

const watchdogTimeout = 30 * 1000;

export class MyWebSocket extends WebSocket {
  private watchdogTimer?: NodeJS.Timeout;

  constructor(
    address: string | URL,
    protocols?: string | string[],
    options?: WebSocket.ClientOptions | ClientRequestArgs
  ) {
    super(address, protocols, options);

    this.on("open", () => this.resetWatchdog());
    this.on("ping", () => this.resetWatchdog());
    this.on("message", () => this.resetWatchdog());
    this.on("close", () => clearTimeout(this.watchdogTimer));
  }

  resetWatchdog() {
    clearTimeout(this.watchdogTimer);
    this.watchdogTimer = setTimeout(() => {
      console.warn("WebSocket watchdog tripped, terminating connection");
      this.terminate();
    }, watchdogTimeout);
  }
}

```

**Comment by KSDaemon** [comment]
thnx for finding another issue. I created a separate issue about incorrect register options.

**Comment by KSDaemon** [comment]
@PatrLind can you try the code from [unhandled-ex](https://github.com/KSDaemon/wampy.js/tree/unhandled-ex) branch and check if it works?
You can set/pass the `onError` wampy instance option to see if such errors are caught and passed to handler.

**Comment by PatrLind** [comment]
Yes, I think it seems to work now with that branch

**Comment by KSDaemon** [comment]
Awesome! Thnx! I'll merge then. And probably publish a patch release later.
