### ISSUE TITLE
Typo in wampy.js:509

### ISSUE THREAD

**Issue by dederer** [KSDaemon/wampy.js#41]
Hi, I think `this._options._authmethods` needs to be changed to `this._options.authmethods` (excess underscore before authmethods).

    508:        if (this._options.authid) {
    509:            options.authmethods = this._options._authmethods;
                                                        ^^^^^^^^^^^^
    510:            options.authid = this._options.authid;
    511:        }

**Comment by KSDaemon** [comment]
Hi @dederer Thanks!
