### ISSUE TITLE
Use with React Native

### ISSUE THREAD

**Issue by beerteam** [KSDaemon/wampy.js#43]
When I use wampy.js with ReactNative with crossbar.io router, have a problem:

`Failed to connect to /127.0.0.1:8080`

I don't use authorization, and other options

```
new Wampy('ws://127.0.0.1:8080', { 
            realm: config.server.realm,
            ws: WebSocket,
            onConnect: () => {
                console.log('Connected to Router!');
            },
            reconnectInterval: 1000,
            maxRetries: 999,
            onClose: function () { console.log('See you next time!'); },
            onError: function (error) { console.log('Breakdown happened', error.message, error); },
            onReconnect: function () { console.log('Reconnecting...'); },
            onReconnectSuccess: function () { console.log('Reconnection succeeded...'); }
        })
```
Can I use wampy with ReactNative. Autobahn don't work with RN. I want use wampy
`ws: WebSocket`
This options I try enabled and disabled, have same result

**Comment by KSDaemon** [comment]
Hi @beerteam! 
Unfortunately, i don't have experience with RN. So i can not test it right now.
Can you provide more details? What WebSocket do you use for communication?
Some logs (both: frontend/backend) will be great!

**Comment by beerteam** [comment]
Судя по имени похоже можно на русском)
У ReactNative своя собственная имплементация Websocket, она [встроенная](https://facebook.github.io/react-native/docs/network.html#websocket-support).
При попытке соединения выбрасывает ошибку в метод onError()
`error.message = Failed to connect to /127.0.0.1:8080`
При этом на самой ноде, правда с autobahnjs все работает хорошо.
Возможно дело в самих RN Websocket

**Comment by KSDaemon** [comment]
@beerteam Lets speak in english here, so other people can seek and read :)
i'm worried about single slash in error message '/127.0.0.1:8080'.

**Comment by beerteam** [comment]
Ok. I used url: 'ws://127.0.0.1:8080'

**Comment by beerteam** [comment]
I ran connection without adb reverse tcp:8080 tcp:8080
Its my problem. Wampy works great
If you will run ReactNative with websockets, run adb reverse tcp:8080 tcp:8080
