### ISSUE TITLE
Is it possible to call RPC with two payloads?

### ISSUE THREAD

**Issue by dederer** [KSDaemon/wampy.js#44]
The [Wampy documentation](https://github.com/KSDaemon/wampy.js#registertopicuri-callbacks) says that register RPC function is called with two payloads:

    rpc. Registered PRC during invocation will receive three arguments: array
    payload (may be undefined), object payload (may be undefined) and options
    object.

However, the [call function](https://github.com/KSDaemon/wampy.js#calltopicuri-payload-callbacks-advancedoptions) allows to call RPC with only one payload:

    call(topicURI[, payload[, callbacks[, advancedOptions]]])

    payload. RPC data. Optional. May be any single value or array or hash-
    table object or null.

The [WAMP specification 9.2.1](https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-9.2.1) has an example:

    [48, 7814135, {}, "com.myapp.user.new", ["johnny"],
           {"firstname": "John", "surname": "Doe"}]

In this example, RPC is called with two payloads (array and hash-table object). Is it implemented in Wampy?

**Comment by KSDaemon** [comment]
Hi @dederer! Well, current Wampy API doesn't allow passing array and object payload at the same time in favor of some kind of sugar. But i'm planning to refactor all payloads for sending and receiving, so it will be supported in next release.

**Comment by dederer** [comment]
Thanks!

**Comment by dederer** [comment]
Hi! Thank you for new version of Wampy. I think it's still not possible to passing array and object payload at the same time. Do you plan to implement it?

**Comment by KSDaemon** [comment]
Hi, @dederer ! Well, actually it is possible! :) I think, i've missed that in documentation. 
You can make it like this:
```
let dictpayload = { key1: 100, key2: 'string-key' },
     payload = { argsList: [1, 2, 3, 4, 5], argsDict: dictpayload };

wampy.call('call.rpc5', payload, function (e) {
   // processing call
                });
```

**Comment by KSDaemon** [comment]
In 6.0 all params as for callbacks, also for api calls were standartized :)

**Comment by dederer** [comment]
Ah, I see :-)
