### ISSUE TITLE
Docs sometime reference the wampy instance as `wampy` and other times as `ws`

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#456]
**Is your feature request related to a problem? Please describe.**
We should probably reference the wampy instance in the docs in a consistent way to avoid confusion

**Describe the solution you'd like**
Renaming `ws` occurences as `wampy`

**Describe alternatives you've considered**
Or renaming `wampy` occurences as `ws`

**Additional context**
None

**Comment by KSDaemon** [comment]
@lucasrmendonca you mean in docs, right? 
I'm +1 for using `wampy`. It's clear what it means. 'Cause `ws` — might be treated as npm websocket package.

**Comment by KSDaemon** [comment]
Great! Thnx!
