### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by jarenal** [KSDaemon/wampy.js#47]
Hi there,

I just installed Wampy using bower but when I load the library using:

`<script src="bower_components/Wampy.js/dist/wampy.js"></script>`

I get the next error message on Javascript console:

> ReferenceError: exports is not defined

The same issue happen if I download the ZIP package from:

[https://github.com/KSDaemon/wampy.js/releases/latest](https://github.com/KSDaemon/wampy.js/releases/latest)

Regards.

**Comment by KSDaemon** [comment]
Hi! Well, i'll check this issue.

**Comment by KSDaemon** [comment]
Hi, @jarenal. Well, dist/wampy.js version is packaged in commonjs module format. So for browser, you can not just include it as you wrote, you need to use some tools, like webpack or similar.

**Comment by KSDaemon** [comment]
btw, i've mentioned this in docs:
In case you are using any kind of build tools and bundlers, like grunt/gulp/webpack/rollup/etc, your entry point can be src/wampy.js if you transpile you code somehow, or dist/wampy.js (default package entry point) which is already transpiled to "es2015" preset, so it is working out of the box, just bundle modules.

**Comment by jarenal** [comment]
Thanks so much for your support @KSDaemon
