### ISSUE TITLE
wampy-all.min.js missed

### ISSUE THREAD

**Issue by jarenal** [KSDaemon/wampy.js#48]
Hi there,

I just installed your library using bower and from the ZIP package but I didn't find the file called **wampy-all.min.js** that you mention in the documentation.

Regards.

**Comment by KSDaemon** [comment]
Hi @jarenal Thanks for pointing out! Well, we dropped this out some time ago, because nowdays all uses loaders, transpilers, build tools, etc. I'll update docs.

**Comment by jarenal** [comment]
You are welcome! Thanks for you quick answer.

**Comment by KSDaemon** [comment]
Hi, @jarenal 
I've updated docs. So just download browser.zip and point to wampy.js from extracted folder!

**Comment by jarenal** [comment]
Thanks so much @KSDaemon I will try it!

**Comment by KSDaemon** [comment]
You are welcome!
