### ISSUE TITLE
Progressive call results

### ISSUE THREAD

**Issue by Jopie64** [KSDaemon/wampy.js#50]
Hi,

I have a question about the progressive call results.
From the docs, I understand that wampy supports progressive call results with registered procedures.
It says:
>Possible attribute of options is "progress": true, which indicates, that it's a progressive result, so there will be more results in future. Be sure to unset "progress" on last result message.

But, I can't find a way how to return more than one result. The docs say how you can delay a return with a promise, but I can't find a way to return a second value after the first one.
It would be nice when the RPC callback can return an rx Observable in addition to a value or a promise. Or is there somehow a different way I missed?

Greetings
Johan

**Comment by KSDaemon** [comment]
Hi @Jopie64! Well, ghmm... You are really right! That was not done properly! Thanks for poining! I've fixed this! For more info see `allows to return progressive results from asynchronous RPC` test

**Comment by Jopie64** [comment]
Thanks for fixing it so quickly! I'm going to try it out.

**Comment by KSDaemon** [comment]
Great! Write me, if you find some problems. I've tested it quickly.

**Comment by Jopie64** [comment]
For now it seems to work quite nicely! Thanks again!
