### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by weiki-li** [KSDaemon/wampy.js#52]
my entry point is dist/wampy.js which is already transpiled to "es2015" preset
but I always get the next error message on Javascript console:
ReferenceError: exports is not defined

**Comment by KSDaemon** [comment]
Hi @weiki-li Can you provide more info, in what console do you get such message? In node or browser? I have no err in node enviroment. Dist version is in commonjs module format, so for browser use you should pack/load it with some tools like webpack or similar.

**Comment by KSDaemon** [comment]
btw, i've mentioned that in docs:
In case you are using any kind of build tools and bundlers, like grunt/gulp/webpack/rollup/etc, your entry point can be src/wampy.js if you transpile you code somehow, or dist/wampy.js (default package entry point) which is already transpiled to "es2015" preset, so it is working out of the box, just bundle modules.

So, basically, es2015 preset does not mean, that code is packed for browser usage.

**Comment by KSDaemon** [comment]
Closing due to be outdated... Feel free to reopen, but do not forget to provide more information :)
