### ISSUE TITLE
TypeError: Wampy is not a constructor with Angular 1.x

### ISSUE THREAD

**Issue by MohamedHedar** [KSDaemon/wampy.js#53]
Hi there ,

I am using Wampy.js with Angular 1.x but i get this error in the initialization 

`TypeError: Wampy is not a constructor`  

any suggestions ?

thanks

**Comment by KSDaemon** [comment]
Hi @MohamedHedar! Can you provide some code, how are you doing?

**Comment by KSDaemon** [comment]
Closing due to be outdated. Feel free to reopen
