### ISSUE TITLE
URI validation does not meet WAMP v2 spec

### ISSUE THREAD

**Issue by pigeonworks** [KSDaemon/wampy.js#54]
According to the WAMP v2 spec URI's must only have numbers, letters and underscore, with a minimum of size of one for each URI component. (https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-02#section-5.1.1.2). The sample regex in the spec is

re.compile(r"^([0-9a-z_]+\.)*([0-9a-z_]+)$")

Wampy however enforces at a minimum size of two for the length of each component. 

    _validateURI (uri) {
        const re = /^([0-9a-zA-Z_]{2,}\.)*([0-9a-zA-Z_]{2,})$/;
        return !(!re.test(uri) || uri.indexOf('wamp') === 0);
    }

This is a mismatch from the spec.

**Comment by KSDaemon** [comment]
Hi! 
Hmm... i do not remember any reason, why i had done so :)
Thanks for pointing. I'm away from net/comp/code for a few days. I'll check it asap.
--
Cheers!
Konstantin четверг, 07 сентября 2017г., 14:02 +03:00 от Rob Thompson  notifications@github.com :

**Comment by pigeonworks** [comment]
no problem. I came across it as I'm generating topics from client data and
it was failing on single characters.
