### ISSUE TITLE
[SERIOUS] Where to get "wampy.min.js" ?

### ISSUE THREAD

**Issue by manatlan** [KSDaemon/wampy.js#55]
In the readme, you say :

"For simple browser usage just download latest browser.zip archive and add wampy-all.min.js file to your page. It contains msgpack encoder plus wampy itself."

But it's not the case : no minimized version (and no usable non minimized) in the ZIP, at least for the v6 version ....

So it's very difficult to test the lib, without grunt/gulp/bower knowledge ;-)

**Comment by KSDaemon** [comment]
Hi! 
Hmm.. Strange... I’m away from inet/comp for a few days. I’ll check it asap.
--
Cheers!
Konstantin понедельник, 11 сентября 2017г., 14:55 +03:00 от manatlan  notifications@github.com :

**Comment by KSDaemon** [comment]
hi, @manatlan!
Yes, indeed, I added browser.zip to gitignore. Now everything is OK. You can take archive files from the master branch. In the future it will be available in the releases.

**Comment by manatlan** [comment]
great ! tested and approved !
thanks ...
(it will be better for non-nodejs people ;-)

**Comment by KSDaemon** [comment]
Great! :)
Well, unfortunately, even just a frontend developers need to know all sorts of webpack/rollup and other things :)
