### ISSUE TITLE
Angular 2 implementation won't connect

### ISSUE THREAD

**Issue by ozorOzora** [KSDaemon/wampy.js#56]
Hi there,

I'm trying to connect my NotificationService (within Angular2) to my Wamp server and so far I've had no feedback from the callbacks. No error or anything.
Basic websocket connection is established when using `var ws = new WebSocket("ws://127.0.0.1:8080")`;
Here is my code:
```
import { Wampy } from 'wampy';

...
export class NotificationService {
   init(){
      this.openWsConnection('ws://127.0.0.1:8080');
   }

   openWsConnection(url): void{
      var ws = new Wampy(url,{
         onConnect: ()=>{
            console.log("connected");
         },
         onClose: ()=>{
            console.log("close");
         },
         onError: ()=>{
            console.log("error");
         },
      });
     console.log(ws);  //ws exists
   }
}
```
Am I missing anything ?

**Comment by KSDaemon** [comment]
Hi, there :)
Well, first of all, you are missing some required options, like realm.
Also, you can check ws.getOpStatus(); after any operation to get more info about last operation

**Comment by ozorOzora** [comment]
Very quick response, thank you!

**Comment by KSDaemon** [comment]
:) No problem! :)
