### ISSUE TITLE
WampyMsgpackSerializer not defined

### ISSUE THREAD

**Issue by ntngl** [KSDaemon/wampy.js#59]
Hi!

I'm using last version of `wampy-all.min.js` from browser.zip and trying to define new instance of wampy with msgpack serializer.
Following the instructions in README.md, I do this:
```javascript
// in browser
ws = new Wampy('ws://mycoolserver.watever:6789/myroute', {
    realm: 'awesome.realm',
    serializer: new WampyMsgpackSerializer(msgpack5)
});
```
So, browser throws error: `Uncaught ReferenceError: WampyMsgpackSerializer is not defined`

Noob question  - am I doing it wrong, or miss something?
Best regards

**Comment by KSDaemon** [comment]
Hi, @ntngl!
Well, indeed, MsgpackSerializer class is not included into browser package.
I'll try to fix it

**Comment by KSDaemon** [comment]
And, btw, you should write `MsgpackSerializer` instead of `WampyMsgpackSerializer' ;)

**Comment by KSDaemon** [comment]
[browser.zip](https://github.com/KSDaemon/wampy.js/files/1401620/browser.zip)
@ntngl Can you try this browser.zip attached?

**Comment by ntngl** [comment]
@KSDaemon I used `wampy-all.min.js` from given archive and all works ok.
Previously, I used `WampyMsgpackSerializer` because of README.md recommends to use it.

Thanks, my issue solved :)

**Comment by KSDaemon** [comment]
Ough! I'll update docs too! :)

**Comment by KSDaemon** [comment]
So, begining with 7d99422 commit updated browser.zip is in master branch
