### ISSUE TITLE
Symbol undefined

### ISSUE THREAD

**Issue by riksnelders** [KSDaemon/wampy.js#62]
On IE and android based Fully kiosk

Symbol undefined && invalidStateError

**Comment by riksnelders** [comment]
fixed. to many wampy instances

**Comment by KSDaemon** [comment]
Hi @riksnelders! Please, provide more information: code with wampy usage, on which string does this errors happened.

**Comment by KSDaemon** [comment]
@riksnelders does this issue still exists? 
Closing for now. Feel free to reopen.
