### ISSUE TITLE
Subscribing with options = {match: 'wildcard'}

### ISSUE THREAD

**Issue by grizmio** [KSDaemon/wampy.js#63]
I'm working on a project using your wampyjs library and crossbar, but I need to use {match: 'wildcard'}.
I fork wampy.js and made a few changes to allow subscribe to foo.bar..baz , but it's not finished, I haven't done the publish part.
Can you read and try this diff and tell me where I need to improve it so you can include the patch on wampy.js?
https://pastebin.com/0uXQrWtF  --- git diff
https://pastebin.com/BwZtYw7j  --- diff

Thanks

**Comment by grizmio** [comment]
In the callback, (info) =>{}
Info=
{ "details": { "publisher": 7578298742437534, "publisher_authid": "foo", "publisher_authrole": "bar", "topic": "cl.fler.cro_1.neweveent" }, "argsList": [ "baz", -1, "xxx",  ] }

**Comment by KSDaemon** [comment]
Hi @grizmio! Great that you are willing to contribute! That is awesome! Thank you!

About your changes:
* Wildcards url are allowed only in one place — subscribing to topics. You have changed `_validateURI` method, which is used everywhere. So this change can cause to pass invalid uris in other places. That is not good. I think, creating a special `_validateSubscribeURI` just for subscribing will be more cleaner.
* About `options` in subscribe method: take a look at `publish` method. Try to be consistent with naming and in place checks. `publish` is a good place to look at.
* Also please add tests for new features.
* btw, just fork repo and create a PR with your changes — that will give us cool github features to review and discuss code.

Feel free to contact me.

**Comment by KSDaemon** [comment]
@grizmio i've just pushed some related updates. Please, sync with master.

**Comment by KSDaemon** [comment]
done it! :)
