### ISSUE TITLE
Something wrong in the wampy.js file (browser.zip release 6.1.0)?

### ISSUE THREAD

**Issue by petten** [KSDaemon/wampy.js#69]
Did you look into the file (under `browser` - seemingly combined from a number of files from the `src` directory) itself?

There are lines very very long, and the top comment section from the original `src/wampy.js` goes way way to the far right (huge indentation) somewhere in the middle (vertically) of now `browser/wampy.js`.

Noticed it after running 'pdoc` (generating documentation from the source) on the file, which failed.

**Comment by petten** [comment]
Same thing in `dist/wampy.js`. The text in `src/wampy.js looks OK, though.

So it appears to be the fault of the build tool; and it does not affect proper functioning of the code.

As to `pdoc`/`rake`, it cannot handle it because it's no good?

**Comment by KSDaemon** [comment]
Well... I think it's rather strange to generate docs from the minified code version. It's prepared for production usage. If you want docs and good readability —  look into original sources.
And, yes, prod version is created using some build tools, so i don't want to dive into them.

**Comment by petten** [comment]
I got around it by changing all appearances of "`/**`" to "`/*`", which probably means that there is nothing (no document) in the file for `pdoc`/`rake` to parse and collect.
