### ISSUE TITLE
Q: Interoperability with wamp routers out there, in particular, bonefish

### ISSUE THREAD

**Issue by petten** [KSDaemon/wampy.js#70]
On the `autobahn|js` page, it has a "Features" section. The very first feature it lists is, quote:

"supports WAMP v2, works with any WAMP server"

Does `wampy.js` works with any WAMP router/server?

The WAMP router in my mind is `bonefish`, in particular.

**Comment by KSDaemon** [comment]
Hi @petten! Of course Wampy.js works with any WAMP v2 router/server! :)

**Comment by petten** [comment]
What about the routers that talk in WAMP v1 only? Such as those listed on this page:

http://wamp-proto.org/implementations/

**Comment by KSDaemon** [comment]
Well, 
* WAMP v1 is OBSOLETE. Do not use it.
* AFAIK, most of the routers (if not all) listed there are WAMP v2 routers.

**Comment by petten** [comment]
In the router list here:

http://wamp-proto.org/implementations/

only two entries explicitly mention `v2`.

But you are probably right in saying that most if not all of the routers are v2.

I just read the spec / RFC, which says that v1 only supports calling topics provided by the router itself. But `bonefish` allows anyone to provide / register topics to be called. That means it's at least in part v2 (if not completely).

**Comment by goeddea** [comment]
@petten - The list of implementations was restarted for WAMP v2. AFAIK all routers and libraries currently listed are WAMP v2.

**Comment by petten** [comment]
@goeddea - Many thanks for your clarification.

For people coming to the party late and not knowing the history, the (implementation list) page and some individual entries do not make it clear they are all v2. In particular, confusion arises when some entries mention (full) v2 (support) whereas others do not mention it at all.

**Comment by petten** [comment]
I was able to use `wampy` to make calls to some callee (which uses the `wampcc` library) through the `bonefish` router.

All three are listed on the official wamp implementation page, and indeed, they are v2.

Thanks you again for having answered my questions.
