### ISSUE TITLE
on reconnect

### ISSUE THREAD

**Issue by riksnelders** [KSDaemon/wampy.js#71]
Does the on reconnect auto subscribe to the old topics? Seems to bug out.
Trying to figure out where its going wrong.

It is suppose to reconnect on all the topics?

**Comment by KSDaemon** [comment]
Hi! Actually "yes", if websocket connection fails after establishing wamp session, and if there are subscriptions — wampy will automatically reconnect and resubscribe/reregister (of course it is configurable through options)

**Comment by KSDaemon** [comment]
@riksnelders Do you still experiencing these problems?

**Comment by riksnelders** [comment]
Nop. Seemed to be a firewall problem with outgoing connections on internal IT structure :)

**Comment by riksnelders** [comment]
Problem doesnt seem to be solved.
If i kill the socket server. and restart it, none of the socket subscribtions are reconnected

**Comment by KSDaemon** [comment]
Can you check following:
1. Initialize wampy instance with debug: true
2. Specify onError collback
3. Check, is onError callback fired during killing websocket server.
4. Also check console. There should be '[wampy] websocket error'

**Comment by riksnelders** [comment]
![image](https://user-images.githubusercontent.com/15074808/37819680-95391a62-2e7e-11e8-8558-6e4cb7a42b45.png)

**Comment by KSDaemon** [comment]
Well. Yep!) This are some external errors.

**Comment by riksnelders** [comment]
Maybe i need some polyfills.. I'll look further into it :)

**Comment by KSDaemon** [comment]
Hi @riksnelders Is your problem solved?

**Comment by KSDaemon** [comment]
Closing due to be outdated
