### ISSUE TITLE
Migrate typings to 6.x.x version

### ISSUE THREAD

**Issue by arm1n** [KSDaemon/wampy.js#72]
Hi there!

Would love to use wampy.js in my current (angular 5.x.x) project as a wamp client - I've just reviewed the current [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wampy/index.d.ts), which seem to be a little bit outdated. Are you planning to migrate them to the latest version 6.x.x?

**Comment by KSDaemon** [comment]
Hi! Yes, of course! Need some time to do it. 
Btw, you can also help with that ;)

**Comment by arm1n** [comment]
Great, thanks for your quick response - will try to get started with the library ASAP, that way I can see what typings are missing and create a pull request :)

**Comment by KSDaemon** [comment]
That will be great! 👍

**Comment by KSDaemon** [comment]
@arm1n Thank again for typings! 👍 Closing for now
