### ISSUE TITLE
Welcome details on connect

### ISSUE THREAD

**Issue by azamat-sharapov** [KSDaemon/wampy.js#73]
Can we have "welcome details" as an argument to `onConnect()` and `onReconnectSuccess()`? It's useful to get some session details once client connects. My current workaround to this is calling `wamp.session.get`, but I would like to avoid odd call, when all needed info is in "welcome".

If you accept PR for this, I could make one.

Thanks!

**Comment by KSDaemon** [comment]
Hi @azamat-sharapov Well, nice feature. Agree. Your PR, will be awesome! :) 
Also it would be great, if you don't forget to fix docs and write (update) test for this feature! 
Thanks!

**Comment by azamat-sharapov** [comment]
Sorry for late reply, finally found some time for this.
