### ISSUE TITLE
React native: Couldn't find preset 'env' relative to directory

### ISSUE THREAD

**Issue by AlexRAV** [KSDaemon/wampy.js#78]
**Describe the bug**
When I import wampy to my react native project, I have got next error:

![ccpsd2jxlty](https://user-images.githubusercontent.com/13298791/41147390-7b52ea6c-6b30-11e8-9e1c-d1a28d487aa2.jpg)

**Comment by KSDaemon** [comment]
Hi! Hm.... I'm not familiar with RN, but as i can see, just reading error description, it says, it can not find env preset. Just install it with `npm i -D babel-preset-env`

**Comment by KSDaemon** [comment]
@AlexRAV Is you problem solved?

**Comment by KSDaemon** [comment]
Seems to be resolved or outdated. Closing for now.
