### ISSUE TITLE
TLS: TLS Client Authentication

### ISSUE THREAD

**Issue by johannwagner** [KSDaemon/wampy.js#80]
**Is your feature request related to a problem? Please describe.**
I just tried to use TLS Client Authentication with autobahn-js. It did not work. I just tapped through the documentation to get an example, how TLS client authentication would work with wampy.js and I could not find an example. There is just an information about magic things, you can configure, which are straight forwarded to node.

**Describe the solution you'd like**
I would like to have an example or more documentation how to use TLS client authentication with wampy.js.

**Describe alternatives you've considered**
I tried to setup wampy to get capable of TLS client authentication, but failed miserably. I also considered to create a pull request at autobahn-js, but I am not enough into topic to create a good solutions.

**Comment by johannwagner** [comment]
@KSDaemon Do you have an ETA? Thanks in Advance!

**Comment by KSDaemon** [comment]
@johannwagner Just for you! :)

**Comment by johannwagner** [comment]
Thanks a lot, but I think, you did not get the problem.

I want to use TLS Client Authentication, which is more than just using TLS on my websocket.
https://crossbar.io/docs/TLS-Client-Certificate-Authentication/

So, my router gets an intermediate CA and assigns all clients with a cert from this intermediate CA an specified authrole. Crossbar implemented and documented this here: https://github.com/crossbario/crossbar-examples/tree/master/authentication/tls/dynamic

Maybe I am just not enough into topic to see, how your documentation archives this..

Best Regards, 
   Johann

**Comment by KSDaemon** [comment]
ookay. May be i've just missed that.
Try this:
```javascript
ws = new Wampy('wss://wamp.router.url:8888/wamp-router', {
    ws: w3cws,
    realm: 'realm1',
    wsRequestOptions: {
        ca: fs.readFileSync('ca-crt.pem'),
        key: fs.readFileSync('client1-key.pem'),
        cert: fs.readFileSync('client1-crt.pem'),
    },
    onConnect: () => {
        console.log('Connected to WAMP Router through TLS!');
    }
});
```

**Comment by johannwagner** [comment]
Thanks! On it!

**Comment by KSDaemon** [comment]
@johannwagner 👍 You're welcome!
