### ISSUE TITLE
'Wampy' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by EmilyRagan** [KSDaemon/wampy.js#89]
I am trying to use wampy in my Angular 5 application. I write in TypeScript with Node.js, so I have also installed @types/wampy. When creating a new wampy instance, I am given the error stated in the title.

1. import required modules
`import { Wampy } from 'wampy';`
`import { w3cws } from 'websocket';`
2. construct new wampy instance
`this.wampClient = new Wampy('myurl');`

I expect to have a working wampy instance, but get the title error on compile. The app still loads in the browser after compile, but the page using this wampy instance does not load and throws an error of `Error: Uncaught (in promise): ReferenceError: Wampy is not defined`

 - OS: macOS High Sierra 10.13.6
 - Node.js v8.10.0
 - Wampy.js 6.2.0
 - Attempting to connect to Crossbar router
 - Angular 5.2.11
 - Angular CLI 1.7.3

**Comment by KSDaemon** [comment]
Hi @EmilyRagan ! 
It seems, there are some errors in ts typings. I'm not a TS guru. You can try to import like `import * as Wampy from 'wampy'`. 
Also have a look at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wampy May be you can find some useful info there.

BTW, will be great, if you could update DefinitelyTyped typings for Wampy! ;)

**Comment by EmilyRagan** [comment]
You're right, it does seem to be an error in the typings. I'm not sure exactly what the problem is yet, so I can't fix it, but uninstalling @types/wampy resolves my issue for now.

I do plan to fork the typings for Wampy, when I have the time, and submitting the updates to DefinitelyTyped.

**Comment by KSDaemon** [comment]
> I do plan to fork the typings for Wampy, when I have the time, and submitting the updates to DefinitelyTyped.

That will be great! Looking forward to ur PR! 👍

**Comment by hawkerm** [comment]
@EmilyRagan I was able to import them without the braces:

```
import Wampy from 'wampy';
import w3cws from 'websocket';
```

But I can't use the `MsgpackSerializer` as there doesn't seem to be a type for it.

```
import MsgpackSerializer from 'wampy/dist/serializers';
```
