### ISSUE TITLE
Additional headers in browser

### ISSUE THREAD

**Issue by ntngl** [KSDaemon/wampy.js#90]
Hi. In some case I need to add some headers to connection request. The docs said that additionalHeaders is for use in Node.js enviroment. How can i pass my own headers in browser?

**Comment by KSDaemon** [comment]
Hi @ntngl! 
Unfortunately thats not possible in browsers :( 
Wampy uses native browser provided Websocket instance. 
See WebSocket description (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)
