### ISSUE TITLE
MsgpackSerializer types?

### ISSUE THREAD

**Issue by hawkerm** [KSDaemon/wampy.js#99]
**Describe the bug**
Trying to use wampy with Typescript in Node.  I was able to import wampy and @types/wampy, but am getting errors with the import for Msgpack:

```
import MsgpackSerializer from 'wampy/dist/serializers';
```

produces error:

> Cannot find module 'wampy/dist/serializers'.

**To Reproduce**
1. Using node TS file, copy example from index page setting up msgpack:

```
import Wampy from 'wampy';
import MsgpackSerializer from 'wampy/dist/serializers';
import w3cws from 'websocket';

const msgpack5 = require('msgpack5');

var ws = new Wampy('ws://socket.server.com:5000/ws', {
    ws: w3cws,
    serializer: new MsgpackSerializer(msgpack5())
});
```
2. Get red-squiggle.

**Expected behavior**
Types part of @types/wampy package?

**Environment (please complete the following information):**
 - OS: Windows 10
 - Node.js 11.10
 - Version of Wampy.js library 6.2.1

**Comment by KSDaemon** [comment]
Hi.
Correct example is:
```
import {Wampy} from 'wampy';
import {MsgpackSerializer} from 'wampy/dist/serializers/MsgpackSerializer';
import {w3cws} from 'websocket';
```
i'll fix the docs.

**Comment by KSDaemon** [comment]
I'm not a ts guru. So it will be great, if you can fix dt.s ;)
